# name of your app (not critical for now)
spring.application.name=iTechSVC-iam-app

# server runs on this port
server.port=8080

# enable auto-restart when files change (DevTools)
spring.devtools.restart.enabled=true

# disable Thymeleaf Html caching so changes on templates show immediately in browser without restarting app
spring.thymeleaf.cache=false

# create a test user (so you don’t depend on random passwords)
#spring.security.user.name=employee - removed since we are now using Okta for authentication instead of Spring Security's in-memory user store

# password for the test user
#spring.security.user.password=Password123 - removed since we are now using Okta for authentication instead of Spring Security's in-memory user store
#spring.security.user.roles=EMPLOYEE - removed since we are now using Okta for authentication instead of Spring Security's in-memory user store
